# Site settings
title: Sardinia Sustainability
email: sardiniasustainability@mail.com
description: "A multi-disciplinary network of people working towards sustainable development in Sardinia, using methods from mathematics and computer science. Not for profit."
keywords:
  - Jekyll

# URL
url: "https://sardiniasustainability.github.io/"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
# google_tag_manager: GTM-XXXXXX
# google_analytics: UA-XXXXXXX-X

# SEO
twitter: sardiniasust
facebook: sardiniasustainability
github: sardiniasustainability
instagram: sardiniasustainability
logo: /assets/logo.svg
image: /assets/logo.svg
social:
  - https://www.facebook.com/sardiniasustainability
  - https://twitter.com/sardiniasust
  - https://github.com/sardiniasustainability

# Sitemap (see sitemap.xml)
sitemap:
  changefreq: weekly

# Build settings
exclude: ["README.md", "Makefile"]

# Collections
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      class: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      class: post

# Plugins
plugins:
  - jekyll-sitemap

# Multiligual
lang:
  - en
  - it
  - srd

# Version (helps with force reloading assets)
version: sparkle
