# Site settings
title: Sustainable Sardinia
email: sustainablesardinia@mail.com
description: "A multi-disciplinary network of people working towards sustainable development in Sardinia, using methods from mathematics and computer science. Not for profit."
keywords:
  - sustainability
  - sustainable development
  - green
  - Sardinia
  - technology
  - data science

# URL
url: "https://sustainablesardinia.github.io"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
google_analytics: G-30EJ8EV134

# Disquis, for comments
disqus: sardinia-sustainability

# SEO
twitter: sustsardinia
facebook: sustainablesardinia
github: sustainablesardinia
instagram: sustsardinia
logo: /assets/logo.png
image: /assets/logo.png
social:
  - https://www.facebook.com/sustainablesardinia
  - https://twitter.com/sustsardinia
  - https://github.com/sustainablesardinia

# Build settings
exclude: ["README.md", "Makefile"]

# Collections
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      class: post
      comments: true
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      class: post
  - scope:
      path: "en"
    values:
      lang: "en" # Set the default language for pages
  - scope:
      path: "it"
    values:
      lang: "it" # Set the default language for pages
  - scope:
      path: "srd"
    values:
      lang: "srd" # Set the default language for pages

# Plugins
plugins:
  - jekyll-sitemap

# Multiligual
languages:
  - en
  - it
  - srd
lang_default: en

# Version (helps with force reloading assets)
version: sparkle

menu:
  - initiative
  - sustainability
  - manifesto
  - projects
  - contacts
