# Site settings
title: Sardinia Sustainability
email: sardiniasustainability@mail.com
description: "A boilerplate set up to create a bilingual Jekyll website."
keywords:
  - Jekyll

# URL
url: "https://sardiniasustainability.github.io/"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
# google_tag_manager: GTM-XXXXXX
# google_analytics: UA-XXXXXXX-X

# SEO
twitter: sardiniasust
facebook: https://www.facebook.com/sardiniasustainability
logo: /assets/logo.png
image: /assets/logo.png
social:
  - https://www.facebook.com/sardiniasustainability
  - https://twitter.com/sardiniasust
  - https://github.com/sardiniasustainability

# Sitemap (see sitemap.xml)
sitemap:
  changefreq: weekly

# Build settings
exclude: ["README.md", "Makefile"]

# Collections
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      class: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      class: post

# Plugins
plugins:
  - jekyll-sitemap

# Multiligual
lang:
  - en
  - fr
  - srd

# Version (helps with force reloading assets)
version: sparkle
# Jekyll+ (not useful if you're running on GitHub pages)
# jekyllplus: Wiredcraft/jekyll-basics/master
